from forgelab.auth.config import AuthSettings


def test_defaults_are_off_and_dev():
    s = AuthSettings()
    assert s.enabled is False
    assert s.mode == "dev"
    assert s.issuer == "forgelab-dev"
    assert s.audience == "forgelab"
    assert s.access_token_ttl == 3600
    assert s.dev_secret  # autogenerated, non-empty


def test_from_env_parses_values():
    env = {
        "FORGELAB_AUTH_ENABLED": "true",
        "FORGELAB_AUTH_MODE": "jwks",
        "FORGELAB_AUTH_ISSUER": "https://idp.example",
        "FORGELAB_AUTH_AUDIENCE": "forge-api",
        "FORGELAB_AUTH_JWKS_URL": "https://idp.example/.well-known/jwks.json",
        "FORGELAB_AUTH_TOKEN_TTL": "120",
        "FORGELAB_AUTH_DEV_SECRET": "shh",
    }
    s = AuthSettings.from_env(env)
    assert s.enabled is True
    assert s.mode == "jwks"
    assert s.issuer == "https://idp.example"
    assert s.audience == "forge-api"
    assert s.jwks_url == "https://idp.example/.well-known/jwks.json"
    assert s.access_token_ttl == 120
    assert s.dev_secret == "shh"


def test_from_env_defaults_when_empty():
    s = AuthSettings.from_env({})
    assert s.enabled is False
    assert s.mode == "dev"
    assert s.issuer == "forgelab-dev"
    assert s.audience == "forgelab"
    assert s.access_token_ttl == 3600
    assert s.dev_secret  # autogenerated, non-empty
    assert s.jwks_url is None
