"""BlenderScriptExporter: ForgeLab threed IR -> a runnable Blender bpy script."""

import ast
import math

from forgelab.exporters.threed.blender_script import BlenderScriptExporter, _camera_location
from forgelab.spec import (
    DocumentMeta,
    Domain,
    ForgeDocument,
    Material,
    Mesh,
    Node,
    Object3D,
    Primitive,
    Transform,
)
from forgelab.spec.threed import NODE_MATERIAL, NODE_MESH, NODE_OBJECT, NODE_SCENE
from forgelab.spec.version import SPEC_VERSION


def _identity_transform():
    return Transform(
        translation=[0.0, 0.0, 0.0], rotation=[0.0, 0.0, 0.0, 1.0], scale=[1.0, 1.0, 1.0]
    )


def _doc(nodes, name="TestScene"):
    return ForgeDocument(
        forgelab_version=SPEC_VERSION,
        domain=Domain.THREED,
        meta=DocumentMeta(name=name, generator="test"),
        nodes=nodes,
    )


def _box_positions(cx=0.0, cy=0.0, cz=0.0, sx=2.0, sy=2.0, sz=2.0):
    hx, hy, hz = sx / 2, sy / 2, sz / 2
    pts = [
        (cx - hx, cy - hy, cz - hz),
        (cx + hx, cy - hy, cz - hz),
        (cx + hx, cy + hy, cz - hz),
        (cx - hx, cy + hy, cz - hz),
        (cx - hx, cy - hy, cz + hz),
        (cx + hx, cy - hy, cz + hz),
        (cx + hx, cy + hy, cz + hz),
        (cx - hx, cy + hy, cz + hz),
    ]
    flat = [c for p in pts for c in p]
    # Two triangles so the mesh has indexed faces (front face only is enough).
    return flat, [0, 1, 2, 0, 2, 3]


def _cylinder_positions(radius=1.0, depth=4.0, n=12, axis=2):
    """Axis-aligned cylinder: two rings of n points + two cap centres."""
    import math

    half = depth / 2
    pts = []
    for plane in (-half, half):
        for i in range(n):
            a = 2 * math.pi * i / n
            ring = [radius * math.cos(a), radius * math.sin(a)]
            p = [0.0, 0.0, 0.0]
            p[axis] = plane
            others = [k for k in (0, 1, 2) if k != axis]
            p[others[0]] = ring[0]
            p[others[1]] = ring[1]
            pts.append(tuple(p))
    for plane in (-half, half):
        c = [0.0, 0.0, 0.0]
        c[axis] = plane
        pts.append(tuple(c))
    return [v for p in pts for v in p]


def _scene():
    return Node(id="scene", type=NODE_SCENE, props={"name": "TestScene"})


def _material():
    return Node(
        id="mat_red",
        type=NODE_MATERIAL,
        props=Material(
            name="vermilion", base_color=[0.8, 0.1, 0.1, 1.0], metallic=0.0, roughness=0.4
        ).model_dump(),
    )


def _object(name, mesh_id):
    return Node(
        id=f"obj_{name}",
        type=NODE_OBJECT,
        props=Object3D(name=name, transform=_identity_transform(), mesh=mesh_id).model_dump(),
    )


def _export(nodes, name="TestScene"):
    return BlenderScriptExporter().from_ir(_doc(nodes, name)).decode("utf-8")


# --------------------------------------------------------------------------- #
# valid Python output
# --------------------------------------------------------------------------- #
def test_output_is_valid_python():
    flat, idx = _box_positions()
    mesh = Node(
        id="m",
        type=NODE_MESH,
        props=Mesh(
            name="cube", primitives=[Primitive(positions=flat, indices=idx, material="mat_red")]
        ).model_dump(),
    )
    src = _export([_scene(), _material(), mesh, _object("Cube", "m")])
    ast.parse(src)  # raises SyntaxError if the script is not valid Python
    assert src.startswith("# Generated by ForgeLab")
    assert "import bpy" in src


# --------------------------------------------------------------------------- #
# materials -> Principled BSDF
# --------------------------------------------------------------------------- #
def test_material_becomes_principled_bsdf():
    flat, idx = _box_positions()
    mesh = Node(
        id="m",
        type=NODE_MESH,
        props=Mesh(
            name="cube", primitives=[Primitive(positions=flat, indices=idx, material="mat_red")]
        ).model_dump(),
    )
    src = _export([_scene(), _material(), mesh, _object("Cube", "m")])
    assert "bpy.data.materials.new(" in src
    assert '"Principled BSDF"' in src
    assert 'bsdf.inputs["Base Color"].default_value = (0.8' in src
    assert 'bsdf.inputs["Metallic"].default_value = 0.0' in src
    assert 'bsdf.inputs["Roughness"].default_value = 0.4' in src
    assert ".data.materials.append(materials['mat_red'])" in src


# --------------------------------------------------------------------------- #
# primitive detection
# --------------------------------------------------------------------------- #
def test_box_mesh_becomes_cube_primitive():
    flat, idx = _box_positions(sx=3.0, sy=3.0, sz=3.0)
    mesh = Node(
        id="m",
        type=NODE_MESH,
        props=Mesh(name="box", primitives=[Primitive(positions=flat, indices=idx)]).model_dump(),
    )
    src = _export([_scene(), mesh, _object("Box", "m")])
    assert "bpy.ops.mesh.primitive_cube_add(size=2.0)" in src
    assert "from_pydata" not in src  # detected, not raw soup
    ast.parse(src)


def test_cylinder_mesh_becomes_cylinder_primitive():
    flat = _cylinder_positions(radius=1.5, depth=4.0, n=16, axis=2)
    mesh = Node(
        id="m",
        type=NODE_MESH,
        props=Mesh(name="cyl", primitives=[Primitive(positions=flat)]).model_dump(),
    )
    src = _export([_scene(), mesh, _object("Cyl", "m")])
    assert "bpy.ops.mesh.primitive_cylinder_add(vertices=16" in src
    assert "from_pydata" not in src
    ast.parse(src)


def test_unrecognized_mesh_falls_back_to_raw():
    # A flat triangle: 3 verts, not a box/cylinder/sphere.
    mesh = Node(
        id="m",
        type=NODE_MESH,
        props=Mesh(
            name="tri",
            primitives=[Primitive(positions=[0, 0, 0, 1, 0, 0, 0, 1, 0], indices=[0, 1, 2])],
        ).model_dump(),
    )
    src = _export([_scene(), mesh, _object("Tri", "m")])
    assert "from_pydata" in src
    assert "primitive_cube_add" not in src
    ast.parse(src)


# --------------------------------------------------------------------------- #
# scene setup: clear, name, camera, three-point lighting
# --------------------------------------------------------------------------- #
def test_scene_is_cleared_and_named():
    # Scene name comes from the scene node's props.name (matches the glTF exporter).
    scene = Node(id="scene", type=NODE_SCENE, props={"name": "MyScene"})
    src = _export([scene], name="ignored-meta-name")
    assert "bpy.ops.object.select_all(action='SELECT')" in src
    assert "bpy.ops.object.delete(use_global=False)" in src
    assert "scene.name = 'MyScene'" in src
    ast.parse(src)


def test_camera_and_three_point_lighting_inserted():
    flat, idx = _box_positions()
    mesh = Node(
        id="m",
        type=NODE_MESH,
        props=Mesh(name="cube", primitives=[Primitive(positions=flat, indices=idx)]).model_dump(),
    )
    src = _export([_scene(), mesh, _object("Cube", "m")])
    assert "bpy.data.cameras.new(" in src
    assert "scene.camera = cam" in src
    assert "TRACK_TO" in src
    assert '_add_light("Key", "AREA"' in src
    assert '_add_light("Fill", "AREA"' in src
    assert '_add_light("Rim", "AREA"' in src
    assert "bpy.context.view_layer.update()" in src
    assert "print(" in src


# --------------------------------------------------------------------------- #
# product-render upgrades: sky world, render engine, camera angle, ground, render
# --------------------------------------------------------------------------- #
def _product_scene_src():
    flat, idx = _box_positions(sx=3.0, sy=3.0, sz=3.0)
    mesh = Node(
        id="m",
        type=NODE_MESH,
        props=Mesh(name="cube", primitives=[Primitive(positions=flat, indices=idx)]).model_dump(),
    )
    return _export([_scene(), mesh, _object("Cube", "m")])


def test_world_uses_nishita_sky_texture():
    src = _product_scene_src()
    assert "ShaderNodeTexSky" in src
    assert "'NISHITA'" in src
    assert "_w_sky.sun_elevation = math.radians(45.0)" in src
    assert "_w_sky.sun_rotation = math.radians(30.0)" in src
    # Background strength is the world strength.
    assert "_w_bg.inputs['Strength'].default_value = 1.0" in src
    ast.parse(src)


def test_render_settings_cycles_resolution_and_denoising():
    src = _product_scene_src()
    assert "scene.render.engine = 'CYCLES'" in src
    assert "scene.cycles.samples = 128" in src
    assert "scene.render.resolution_x = 1920" in src
    assert "scene.render.resolution_y = 1080" in src
    assert "scene.cycles.use_denoising = True" in src
    # OpenImageDenoise is the primary denoiser (Blender 3.5+); NLM is the fallback.
    assert "scene.cycles.denoiser = 'OPENIMAGEDENOISE'" in src
    assert src.index("'OPENIMAGEDENOISE'") < src.index("'NLM'")


def test_preview_flag_toggles_eevee():
    src = _product_scene_src()
    assert "PREVIEW = True" in src
    assert "if PREVIEW:" in src
    # Preview path uses EEVEE with 64 samples; quality path uses CYCLES.
    assert "BLENDER_EEVEE" in src
    assert "taa_render_samples = 64" in src


def test_camera_is_85mm_at_three_quarter_angle():
    src = _product_scene_src()
    assert "cam_data.lens = 85.0" in src
    # The placement helper must put the camera at azimuth 45deg, elevation 30deg
    # (computed in the IR's Y-up space: azimuth in the X/Z plane, elevation in Y).
    center = (0.0, 0.0, 0.0)
    radius = 4.0
    x, y, z = _camera_location(center, radius)
    assert round(math.degrees(math.atan2(x, z)), 6) == 45.0
    dist = math.dist((x, y, z), center)
    assert round(math.degrees(math.asin(y / dist)), 6) == 30.0
    assert round(dist / radius, 6) == 4.5  # distance scaled to the bounding sphere


def test_ground_plane_present():
    src = _product_scene_src()
    assert "bpy.ops.mesh.primitive_plane_add(" in src
    assert "ForgeLab_Ground" in src
    assert "_gbsdf.inputs['Roughness'].default_value = 0.8" in src


def test_render_output_line_present():
    src = _product_scene_src()
    assert "bpy.ops.render.render(write_still=True)" in src
    assert ".replace('.py', '_render.png')" in src
    ast.parse(src)


# --------------------------------------------------------------------------- #
# registry + MCP wiring
# --------------------------------------------------------------------------- #
def test_registered_in_default_registry():
    from forgelab.core import default_registry

    exporter = default_registry().get_exporter("blender_script")
    assert exporter is BlenderScriptExporter


def test_list_formats_includes_blender_script():
    from forgelab.mcp import tools

    formats = tools.list_formats()
    assert formats["blender_script"]["export"] is True
